### PR TITLE
Updating to work with celery 3.x

### PR DESCRIPTION
**Pull request by bdeggleston**
celery 2.3 had a state object declared in the state module:
https://github.com/celery/celery/blob/v2.3.0/celery/events/state.py#L314

celerymon depended on this, but it was removed in a later version of celery. This pull request adds celerymon's own state object.

It also updates the api's json decorator to unroll generators

### CODE REVIEW

**Comment by jaapz** [comment]
Can this be merged? Celerymon on pip is still broken if you use the newer version of celery...

**Comment by ajferrick** [comment]
+1 can this be merged, please?

**Comment by BrunoDesthuilliers** [comment]
+1 - or make clear that celerymon is not supported anymore ?

**Comment by ask** [comment]
Thanks! It's not really supported as flower has taken over the role of celerymon, and does much more, but cannot see any harm in merging this fine work!

Merged into master

**Comment by jaapz** [comment]
Thanks @ask !

**Comment by ajferrick** [comment]
@ask :trophy:

**Pull request merged**
